### ISSUE TITLE
Lookup does'nt find Entries after update

### ISSUE THREAD

**Issue by Juergen-aus-Zuendorf** [gkrid/dokuwiki-plugin-structcombolookup#2]
Hi,

the struct type "Lookup" does'nt find entries after update 2020-05-14.

For more details I would like to refer to a ticket on the struct plugin, where I already explained the problem and where Annda is currently working on:
https://github.com/cosmocode/dokuwiki-plugin-struct/pull/503

Best regards
Juergen

**Comment by solewniczak** [comment]
[This commit](https://github.com/cosmocode/dokuwiki-plugin-struct/commit/17124890cbddd6bfbea44324d3384271df231ce4) fixes the problem but the 16th migration must be rerun in order to migrate the ComboLookup fields correctly.

**Comment by solewniczak** [comment]
Maybe the 17th migration fixes the problem I haven't check it yet.

**Comment by Juergen-aus-Zuendorf** [comment]
Thank you. 
The functionality is restored for newly entered data, but the old data is still lost.

**Comment by solewniczak** [comment]
There is no other option currently than rerunning the struct migration on old database and then merging the two databases manually. The bug concerns only the users that ran the migration before [this commit](https://github.com/cosmocode/dokuwiki-plugin-struct/commit/17124890cbddd6bfbea44324d3384271df231ce4). When the migration was run after the commit, there should be no issues.

**Comment by Juergen-aus-Zuendorf** [comment]
Bummer, I guess I'll have to manually repair a few hundred records!

But thank you for your response

**Comment by solewniczak** [comment]
Ok, a few hundred is not worth of manual update. I'll try to help you :) Have you already update your struct  database to version "17"?

**Comment by Juergen-aus-Zuendorf** [comment]
Oh, thank you!

The struct plugin has version 2020-06-08, the sqlite plugin has 2020-04-09. Is that what you mean? Or please give me a hint where I can see the database version.

**Comment by solewniczak** [comment]
I assume you have sqlite3 client installed. Then run the following command in the main dokuwiki directory:
`sqlite3 data/meta/struct.sqlite3 'SELECT * FROM opts;'`
It should give you your struct database version. If it is not: "17", please make a backup of your wiki and update the struct plugin to the last version.

**Comment by Juergen-aus-Zuendorf** [comment]
Yes, dbversion is 17

**Comment by solewniczak** [comment]
Try to manually replace database version with "17" and then open some wiki page with struct data. It should run the migration again and helpfully migrate bad records. Make a backup of your "struct.sqlite3" file before that. You can update dbversion using folowing sql command:
`UPDATE opts SET val=16 WHERE opt='dbversion';`

**Comment by Juergen-aus-Zuendorf** [comment]
To be on the safe side, I would like to ask again:
1.) Create a backup of the file "struct.sqlite3"
2.) Enter the command "UPDATE opts SET val=16 WHERE opt='dbversion';" into the SQL interface of the dokuwiki admin console
3.) Edit any page with struct data
Is that right?

**Comment by solewniczak** [comment]
1) Yes
2) Yes
3) You only need to access a page with struct data, not nessesery edit it.

I'm not 100% sure that it will fix the problem, but this is one of my ideas. If not, we will try another solutions.

**Comment by Juergen-aus-Zuendorf** [comment]
Sorry, but nothing happens. I only get the following message in the sql console of the admin page:
`0 affected rows in 0.00640 seconds`
And the struct values aren't updated.

**Comment by solewniczak** [comment]
Try to update your plug-in using this branch: https://github.com/gkrid/dokuwiki-plugin-structcombolookup/tree/migration-fix

This branch adds an migration fix that should migrate your ComboLookups correctly. Before upgrading the plugin make a backup of your struct.sqlite3 file first.

**Comment by solewniczak** [comment]
After upgrading the plugin touch your config file in order to remove the pages cache:

`sudo touch conf/local.php`

and then visit any page with struct table.

**Comment by Juergen-aus-Zuendorf** [comment]
You write

`sudo touch conf/local.php`

I don't have direct access to the server. Dokuwiki is only mapped as a Windows drive for me. Is it enough to save the configuration instead?

**Comment by solewniczak** [comment]
Yes, you can save the configuration. It will have the same effect.

**Comment by Juergen-aus-Zuendorf** [comment]
That's it!
Thank you very much!!!

**Comment by solewniczak** [comment]
You're welcome :) You can now go back to the master branch of the plugin.

**Comment by Juergen-aus-Zuendorf** [comment]
Thank you very much
